# Generated by Django 5.1.7 on 2025-03-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='delivery_time',
            field=models.PositiveIntegerField(help_text='Delivery time in days'),
        ),
    ]
